---
- name: Ensure systems are DISA STIG compliant
  hosts: all
  become: yes

  roles:
    - { role: RHEL7-STIG, 
#        rhel7stig_cat1_audit: yes,
#        rhel7stig_cat2_audit: no,
#        rhel7stig_cat3_audit: no,
#        rhel7stig_cat1_patch: no,
#        rhel7stig_cat2_patch: no,
#        rhel7stig_cat3_patch: no,
        when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
      }

#- include: ./examples/apache-basic-playbook/site.yml
